backend:
  name: github
  repo: arhange-l/project_mu
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "gallery"
    label: "Галерея"
    folder: "assets/uploads"
    create: true
    slug: "{{slug}}"
    fields:
      - {name: "image", label: "Фото", widget: "image"}
      - {name: "caption", label: "Подпись", widget: "string"}
